<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sophia Emerson">
<meta name="dcterms.date" content="2024-07-26">

<title>The Impact of Education and Work Experience on Wages: A Comprehensive Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="..\..\paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Impact of Education and Work Experience on Wages: A Comprehensive Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sophia Emerson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 26, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This study examines the returns to education and work experience in the contemporary labor market, focusing on heterogeneity across the wage distribution and between genders. Using a rich dataset of 1,647 individuals, we employ OLS and quantile regression techniques to analyze the impact of human capital investments on hourly wages. Our findings reveal that an additional year of education is associated with an 8.1% increase in wages, while an extra year of experience yields a 3.8% increase, with diminishing returns over time. Quantile regressions show that education has a slightly stronger impact on wages at the lower end of the distribution, while experience yields the highest returns at the 25th percentile. Gender-specific analyses reveal higher returns to both education and experience for women compared to men, challenging traditional narratives. However, a substantial gender wage gap persists, and marriage has divergent effects on wages for men and women. These results underscore the continued importance of human capital investments in determining labor market outcomes, while highlighting persistent gender disparities. Our findings have important implications for educational policy, labor market interventions, and efforts to address wage inequality, emphasizing the need for nuanced approaches that consider the complexities of modern labor markets.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The relationship between human capital investments and labor market outcomes has been a cornerstone of economic research for decades. Understanding how education and work experience influence wages is crucial for policymakers, employers, and individuals alike. This paper contributes to this body of knowledge by examining the returns to education and experience in a contemporary labor market context, with a particular focus on heterogeneity across the wage distribution and between genders.</p>
<p>Building on the seminal works of <span class="citation" data-cites="becker1964human">Becker (<a href="#ref-becker1964human" role="doc-biblioref">1964</a>)</span> and <span class="citation" data-cites="mincer1974schooling">Mincer (<a href="#ref-mincer1974schooling" role="doc-biblioref">1974</a>)</span>, our study employs a rich dataset to investigate the nuanced ways in which education and experience shape earnings. We extend the traditional Mincerian wage equation by incorporating quantile regression techniques, allowing us to examine how returns to human capital vary across different points of the wage distribution. Furthermore, we conduct separate analyses for men and women to shed light on persistent gender disparities in the labor market.</p>
<p>Our research addresses several key questions:</p>
<ol type="1">
<li>What are the current returns to education and experience in the labor market?</li>
<li>How do these returns vary across the wage distribution?</li>
<li>To what extent do gender differences persist in the returns to education and experience?</li>
<li>How do other factors, such as marital status and number of children, interact with these returns?</li>
</ol>
<p>By addressing these questions, our study contributes to the ongoing dialogue about human capital investment, wage determination, and gender equality in the workplace. Our findings have important implications for educational policy, labor market interventions, and our understanding of persistent wage gaps.</p>
<p>The paper is structured as follows: Section 2 provides a review of the relevant literature. Section 3 describes our data and methodology. Section 4 presents our empirical results, including main regression analyses and robustness checks. Finally, Section 5 concludes with a discussion of the implications of our findings and directions for future research.</p>
</section>
<section id="literature-review" class="level1">
<h1>Literature Review</h1>
<p>The relationship between education, work experience, and wages has been a central focus in labor economics for decades. Human capital theory, pioneered by <span class="citation" data-cites="becker1964human">Becker (<a href="#ref-becker1964human" role="doc-biblioref">1964</a>)</span> and <span class="citation" data-cites="mincer1974schooling">Mincer (<a href="#ref-mincer1974schooling" role="doc-biblioref">1974</a>)</span>, posits that individuals invest in education and on-the-job training to enhance their productivity and, consequently, their earnings potential.</p>
<p>Numerous empirical studies have validated the positive impact of education on wages. <span class="citation" data-cites="card1999causal">Card (<a href="#ref-card1999causal" role="doc-biblioref">1999</a>)</span> conducted a comprehensive review of the literature and found that an additional year of schooling typically increases earnings by 6-10%. This finding has been corroborated by subsequent research, including <span class="citation" data-cites="psacharopoulos2018returns">Psacharopoulos and Patrinos (<a href="#ref-psacharopoulos2018returns" role="doc-biblioref">2018</a>)</span>, who analyzed global returns to education and found an average private return of 8.8% per year of schooling.</p>
<p>Work experience has also been shown to significantly influence wages. <span class="citation" data-cites="mincer1974schooling">Mincer (<a href="#ref-mincer1974schooling" role="doc-biblioref">1974</a>)</span>’s seminal earnings function highlighted the importance of experience in shaping an individual’s earnings profile. The relationship between experience and wages is often found to be concave, with returns diminishing over time. <span class="citation" data-cites="murphy1992structure">Murphy and Welch (<a href="#ref-murphy1992structure" role="doc-biblioref">1992</a>)</span> examined this pattern across different cohorts and skill levels, finding that the experience-earnings profile has become steeper for more educated workers over time.</p>
<p>The interplay between education and experience has been explored by several researchers. <span class="citation" data-cites="altonji1993effects">Altonji (<a href="#ref-altonji1993effects" role="doc-biblioref">1993</a>)</span> found that the returns to education are higher for individuals with more work experience, suggesting a complementarity between the two forms of human capital. This finding was further supported by <span class="citation" data-cites="dustmann2004returns">Dustmann and Van Soest (<a href="#ref-dustmann2004returns" role="doc-biblioref">2004</a>)</span>, who examined the returns to education and experience for immigrants in Germany.</p>
<p>Gender differences in returns to education and experience have also been a subject of extensive research. <span class="citation" data-cites="blau2017gender">Blau and Kahn (<a href="#ref-blau2017gender" role="doc-biblioref">2017</a>)</span> conducted a comprehensive review of the gender wage gap literature, finding that while the gap has narrowed over time, significant differences persist in the returns to education and experience between men and women.</p>
<p>Recent studies have also explored the role of job tenure in wage determination. <span class="citation" data-cites="topel1991specific">Topel (<a href="#ref-topel1991specific" role="doc-biblioref">1991</a>)</span> found that wages rise with job seniority, even after controlling for general labor market experience. However, <span class="citation" data-cites="altonji2013heterogeneity">Altonji, Blom, and Meghir (<a href="#ref-altonji2013heterogeneity" role="doc-biblioref">2013</a>)</span> challenged this finding, arguing that much of the apparent return to tenure is due to job match quality rather than firm-specific human capital accumulation.</p>
<p>In summary, while the positive impacts of education and experience on wages are well-established, the magnitude of these effects, their potential complementarities, and their variation across different demographic groups remain active areas of research in labor economics.</p>
</section>
<section id="summary-statistics" class="level1">
<h1>Summary Statistics</h1>
<p><a href="#tbl-sumstat" class="quarto-xref">Table&nbsp;1</a> presents the descriptive statistics for the key variables in our analysis. The sample consists of 1,647 individuals, with some variation in the number of observations across variables due to missing data.</p>
<p>The mean log hourly wage is 3.4, with a standard deviation of 0.5. On average, respondents have 11.4 years of education, with a standard deviation of 2.4 years. The average work experience is 13.2 years, with a considerable variation as indicated by the standard deviation of 10 years. Job tenure, which measures the time spent with the current employer, averages 7.9 years with a standard deviation of 8.1 years.</p>
<div id="tbl-sumstat" class="quarto-float anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sumstat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Descriptive Statistics of Key Variables
</figcaption>
<div aria-describedby="tbl-sumstat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 35%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Mean</th>
<th style="text-align: center;">StdDev</th>
<th style="text-align: center;">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Log hourly wages</td>
<td style="text-align: center;">3.4</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1434</td>
</tr>
<tr class="even">
<td>Yrs of education</td>
<td style="text-align: center;">11.4</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">1647</td>
</tr>
<tr class="odd">
<td>Yrs of experience</td>
<td style="text-align: center;">13.2</td>
<td style="text-align: center;">10.0</td>
<td style="text-align: center;">1434</td>
</tr>
<tr class="even">
<td>Yrs of job tenure</td>
<td style="text-align: center;">7.9</td>
<td style="text-align: center;">8.1</td>
<td style="text-align: center;">1434</td>
</tr>
<tr class="odd">
<td>Sex of respondent</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1647</td>
</tr>
<tr class="even">
<td>Labor force participation</td>
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">1647</td>
</tr>
<tr class="odd">
<td>Age in yrs</td>
<td style="text-align: center;">39.3</td>
<td style="text-align: center;">11.0</td>
<td style="text-align: center;">1647</td>
</tr>
<tr class="even">
<td>No of children &lt;6</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">1647</td>
</tr>
<tr class="odd">
<td>No of children 7-14</td>
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">1647</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The sample is relatively balanced in terms of gender, with females representing approximately 50% of the respondents. Labor force participation is high, with a mean of 0.9 and a standard deviation of 0.3, indicating that most respondents are active in the labor market.</p>
<p>The average age of respondents is 39.3 years, with a standard deviation of 11 years, suggesting a wide age range in the sample. Regarding family composition, respondents have on average 0.3 children under 6 years old and 0.3 children between 7 and 14 years old, both with standard deviations of 0.7.</p>
<p>These summary statistics provide a comprehensive overview of the sample characteristics and set the stage for our subsequent regression analyses.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<section id="empirical-strategy" class="level2">
<h2 class="anchored" data-anchor-id="empirical-strategy">Empirical Strategy</h2>
<p>Our empirical strategy is grounded in the human capital theory framework developed by <span class="citation" data-cites="becker1964human">Becker (<a href="#ref-becker1964human" role="doc-biblioref">1964</a>)</span> and <span class="citation" data-cites="mincer1974schooling">Mincer (<a href="#ref-mincer1974schooling" role="doc-biblioref">1974</a>)</span>. We extend the traditional Mincerian wage equation to include additional control variables and to explore potential non-linearities in the returns to experience. Our baseline model specification is as follows:</p>
<p><span class="math display">\[\ln(w_i) = \beta_0 + \beta_1 \text{educ}_i + \beta_2 \text{exp}_i + \beta_3 \text{exp}_i^2 + \gamma X_i + \epsilon_i\]</span></p>
<p>where <span class="math inline">\(\ln(w_i)\)</span> is the natural logarithm of hourly wages for individual <span class="math inline">\(i\)</span>, <span class="math inline">\(\text{educ}_i\)</span> represents years of education, <span class="math inline">\(\text{exp}_i\)</span> denotes years of work experience, <span class="math inline">\(X_i\)</span> is a vector of control variables including gender, age, marital status, number of children, and job tenure, and <span class="math inline">\(\epsilon_i\)</span> is the error term. The quadratic term for experience (<span class="math inline">\(\text{exp}_i^2\)</span>) is included to capture the potential diminishing returns to experience over time, as suggested by previous literature <span class="citation" data-cites="murphy1992structure">(<a href="#ref-murphy1992structure" role="doc-biblioref">Murphy and Welch 1992</a>)</span>.</p>
<section id="ordinary-least-squares-estimation" class="level3">
<h3 class="anchored" data-anchor-id="ordinary-least-squares-estimation">Ordinary Least Squares Estimation</h3>
<p>We begin our analysis by estimating the model using Ordinary Least Squares (OLS) regression. This provides us with average returns to education and experience across the entire sample, serving as a baseline for comparison with more nuanced analyses.</p>
</section>
<section id="quantile-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="quantile-regression-analysis">Quantile Regression Analysis</h3>
<p>To examine how returns to education and experience may vary across the wage distribution, we employ quantile regression techniques <span class="citation" data-cites="koenker1978">(<a href="#ref-koenker1978" role="doc-biblioref">Koenker and Bassett 1978</a>)</span>. Specifically, we estimate our model at the 25th, 50th (median), and 75th percentiles of the wage distribution. The quantile regression model is specified as:</p>
<p><span class="math display">\[Q_{\tau}(\ln(w_i)|X_i) = \beta_0(\tau) + \beta_1(\tau) \text{educ}_i + \beta_2(\tau) \text{exp}_i + \beta_3(\tau) \text{exp}_i^2 + \gamma(\tau) X_i\]</span></p>
<p>where <span class="math inline">\(Q_{\tau}(\ln(w_i)|X_i)\)</span> represents the <span class="math inline">\(\tau\)</span>th conditional quantile of <span class="math inline">\(\ln(w_i)\)</span> given <span class="math inline">\(X_i\)</span>. This approach allows us to capture potential heterogeneity in returns that may be obscured by OLS estimates, providing insights into how the impact of human capital investments may differ across wage levels.</p>
</section>
<section id="gender-specific-analyses" class="level3">
<h3 class="anchored" data-anchor-id="gender-specific-analyses">Gender-Specific Analyses</h3>
<p>To investigate potential gender differences in returns to education and experience, we estimate separate regressions for men and women. This allows us to examine how the impact of human capital investments and other factors may differ between genders, contributing to our understanding of persistent wage gaps in the labor market.</p>
</section>
</section>
</section>
<section id="data-analysis-and-results" class="level1">
<h1>Data Analysis and Results</h1>
<p>Our analysis employs several regression models to examine the impact of education and work experience on wages, while controlling for various demographic and job-related factors. <a href="#tbl-mainreg" class="quarto-xref">Table&nbsp;2</a> presents the results from our main regression analyses, including Ordinary Least Squares (OLS) and quantile regressions at the 25th, 50th, and 75th percentiles.</p>
<section id="main-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="main-regression-results">Main Regression Results</h2>
<p>The OLS results in <a href="#tbl-mainreg" class="quarto-xref">Table&nbsp;2</a> show that an additional year of education is associated with an 8.1% increase in hourly wages, significant at the 0.1% level. This finding is consistent with previous literature, such as <span class="citation" data-cites="card1999causal">Card (<a href="#ref-card1999causal" role="doc-biblioref">1999</a>)</span>, who found returns to education typically ranging from 6-10%.</p>
<div id="tbl-mainreg" class="quarto-float anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mainreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Main Regression Results
</figcaption>
<div aria-describedby="tbl-mainreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">OLS</th>
<th style="text-align: center;">Qreg(25)</th>
<th style="text-align: center;">Qreg(50)</th>
<th style="text-align: center;">Qreg(75)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yrs of education</td>
<td style="text-align: center;">0.081<sup>***</sup></td>
<td style="text-align: center;">0.078<sup>***</sup></td>
<td style="text-align: center;">0.069<sup>***</sup></td>
<td style="text-align: center;">0.064<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.007)</td>
<td style="text-align: center;">(0.005)</td>
<td style="text-align: center;">(0.005)</td>
<td style="text-align: center;">(0.003)</td>
</tr>
<tr class="odd">
<td>Yrs of experience</td>
<td style="text-align: center;">0.038<sup>***</sup></td>
<td style="text-align: center;">0.046<sup>***</sup></td>
<td style="text-align: center;">0.022<sup>***</sup></td>
<td style="text-align: center;">0.021<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.006)</td>
<td style="text-align: center;">(0.008)</td>
<td style="text-align: center;">(0.004)</td>
<td style="text-align: center;">(0.003)</td>
</tr>
<tr class="odd">
<td>Experience<sup>2</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
</tr>
<tr class="odd">
<td>Sex of respondent</td>
<td style="text-align: center;">-0.198<sup>***</sup></td>
<td style="text-align: center;">-0.272<sup>***</sup></td>
<td style="text-align: center;">-0.142<sup>***</sup></td>
<td style="text-align: center;">-0.133<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.031)</td>
<td style="text-align: center;">(0.035)</td>
<td style="text-align: center;">(0.025)</td>
<td style="text-align: center;">(0.021)</td>
</tr>
<tr class="odd">
<td>Age in yrs</td>
<td style="text-align: center;">0.014<sup>***</sup></td>
<td style="text-align: center;">0.013<sup>***</sup></td>
<td style="text-align: center;">0.012<sup>***</sup></td>
<td style="text-align: center;">0.015<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.002)</td>
<td style="text-align: center;">(0.002)</td>
<td style="text-align: center;">(0.002)</td>
<td style="text-align: center;">(0.001)</td>
</tr>
<tr class="odd">
<td>No of children &lt;6</td>
<td style="text-align: center;">0.088<sup>***</sup></td>
<td style="text-align: center;">0.075<sup>***</sup></td>
<td style="text-align: center;">0.049<sup>*</sup></td>
<td style="text-align: center;">0.043<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.020)</td>
<td style="text-align: center;">(0.019)</td>
<td style="text-align: center;">(0.020)</td>
<td style="text-align: center;">(0.011)</td>
</tr>
<tr class="odd">
<td>No of children 7-14</td>
<td style="text-align: center;">0.031</td>
<td style="text-align: center;">0.022</td>
<td style="text-align: center;">0.013</td>
<td style="text-align: center;">0.036<sup>*</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.020)</td>
<td style="text-align: center;">(0.026)</td>
<td style="text-align: center;">(0.018)</td>
<td style="text-align: center;">(0.016)</td>
</tr>
<tr class="odd">
<td>Married</td>
<td style="text-align: center;">0.004</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">0.037</td>
<td style="text-align: center;">0.007</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.033)</td>
<td style="text-align: center;">(0.046)</td>
<td style="text-align: center;">(0.030)</td>
<td style="text-align: center;">(0.024)</td>
</tr>
<tr class="odd">
<td>Divorced</td>
<td style="text-align: center;">0.087</td>
<td style="text-align: center;">-0.027</td>
<td style="text-align: center;">0.028</td>
<td style="text-align: center;">0.056</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.046)</td>
<td style="text-align: center;">(0.056)</td>
<td style="text-align: center;">(0.048)</td>
<td style="text-align: center;">(0.054)</td>
</tr>
<tr class="odd">
<td>Constant</td>
<td style="text-align: center;">1.668<sup>***</sup></td>
<td style="text-align: center;">1.523<sup>***</sup></td>
<td style="text-align: center;">2.014<sup>***</sup></td>
<td style="text-align: center;">2.183<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.102)</td>
<td style="text-align: center;">(0.115)</td>
<td style="text-align: center;">(0.069)</td>
<td style="text-align: center;">(0.051)</td>
</tr>
<tr class="odd">
<td>Observations</td>
<td style="text-align: center;">1434</td>
<td style="text-align: center;">1434</td>
<td style="text-align: center;">1434</td>
<td style="text-align: center;">1434</td>
</tr>
<tr class="even">
<td><em>R</em><sup>2</sup></td>
<td style="text-align: center;">0.373</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Note: <sup>*</sup> <em>p</em> &lt; 0.05, <sup>**</sup> <em>p</em> &lt; 0.01, <sup>***</sup> <em>p</em> &lt; 0.001</p>
</div>
</figure>
</div>
<p>Years of work experience also show a positive and significant relationship with wages, with each additional year associated with a 3.8% increase in hourly wages. However, the negative coefficient on the squared term of experience (-0.001) indicates diminishing returns to experience, aligning with the concave experience-earnings profile described by <span class="citation" data-cites="murphy1992structure">Murphy and Welch (<a href="#ref-murphy1992structure" role="doc-biblioref">1992</a>)</span>.</p>
<p>The gender wage gap is evident in our results, with females earning approximately 19.8% less than males, ceteris paribus. This substantial gap underscores the persistence of gender wage disparities, as discussed in <span class="citation" data-cites="blau2017gender">Blau and Kahn (<a href="#ref-blau2017gender" role="doc-biblioref">2017</a>)</span>.</p>
<p>Age shows a positive relationship with wages, with each additional year associated with a 1.4% increase in hourly wages. Interestingly, the number of children under 6 years old is positively associated with wages, possibly reflecting a selection effect where higher-earning individuals are more likely to have young children.</p>
</section>
<section id="quantile-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="quantile-regression-results">Quantile Regression Results</h2>
<p>The quantile regression results in <a href="#tbl-mainreg" class="quarto-xref">Table&nbsp;2</a> provide insights into how the effects of education and experience vary across the wage distribution. The returns to education are highest at the lower end of the distribution (7.8% at the 25th percentile) and decrease slightly for higher quantiles (6.4% at the 75th percentile). This pattern suggests that education has a slightly stronger impact on wages for lower-earning individuals.</p>
<p>The returns to experience show more variation across quantiles, with the highest returns at the 25th percentile (4.6%) and lower returns at the median and 75th percentile (2.2% and 2.1%, respectively). This finding suggests that additional experience is particularly valuable for individuals at the lower end of the wage distribution.</p>
<p>The gender wage gap is most pronounced at the 25th percentile (-27.2%) and less severe at higher quantiles (-13.3% at the 75th percentile), indicating that gender disparities are particularly stark among lower-earning individuals.</p>
</section>
<section id="robustness-checks-and-subgroup-analysis" class="level2">
<h2 class="anchored" data-anchor-id="robustness-checks-and-subgroup-analysis">Robustness Checks and Subgroup Analysis</h2>
<p><a href="#tbl-secreg" class="quarto-xref">Table&nbsp;3</a> presents the results of our robustness checks, including separate regressions for men and women. These analyses reveal important gender differences in the returns to education and experience.</p>
<p>The returns to education are higher for women (9.8%) compared to men (5.7%). This finding aligns with recent literature suggesting that women’s returns to education have surpassed those of men in many contexts <span class="citation" data-cites="diprete2006cumulative">(<a href="#ref-diprete2006cumulative" role="doc-biblioref">DiPrete and Buchmann 2006</a>)</span>.</p>
<div id="tbl-secreg" class="quarto-float anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-secreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Main Regression Results
</figcaption>
<div aria-describedby="tbl-secreg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">OLS</th>
<th style="text-align: center;">Men</th>
<th style="text-align: center;">Women</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yrs of education</td>
<td style="text-align: center;">0.081<sup>***</sup></td>
<td style="text-align: center;">0.057<sup>***</sup></td>
<td style="text-align: center;">0.098<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.007)</td>
<td style="text-align: center;">(0.009)</td>
<td style="text-align: center;">(0.010)</td>
</tr>
<tr class="odd">
<td>Yrs of experience</td>
<td style="text-align: center;">0.038<sup>***</sup></td>
<td style="text-align: center;">0.030<sup>***</sup></td>
<td style="text-align: center;">0.062<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.006)</td>
<td style="text-align: center;">(0.007)</td>
<td style="text-align: center;">(0.010)</td>
</tr>
<tr class="odd">
<td>Experience<sup>2</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
<td style="text-align: center;">-0.001<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
<td style="text-align: center;">(0.000)</td>
</tr>
<tr class="odd">
<td>Sex of respondent</td>
<td style="text-align: center;">-0.198<sup>***</sup></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.031)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>Age in yrs</td>
<td style="text-align: center;">0.014<sup>***</sup></td>
<td style="text-align: center;">0.023<sup>***</sup></td>
<td style="text-align: center;">0.005</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.002)</td>
<td style="text-align: center;">(0.002)</td>
<td style="text-align: center;">(0.004)</td>
</tr>
<tr class="odd">
<td>No of children &lt;6</td>
<td style="text-align: center;">0.088<sup>***</sup></td>
<td style="text-align: center;">0.034</td>
<td style="text-align: center;">0.189<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.020)</td>
<td style="text-align: center;">(0.019)</td>
<td style="text-align: center;">(0.041)</td>
</tr>
<tr class="odd">
<td>No of children 7-14</td>
<td style="text-align: center;">0.031</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.050</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.020)</td>
<td style="text-align: center;">(0.021)</td>
<td style="text-align: center;">(0.033)</td>
</tr>
<tr class="odd">
<td>Married</td>
<td style="text-align: center;">0.004</td>
<td style="text-align: center;">0.132<sup>***</sup></td>
<td style="text-align: center;">-0.155<sup>**</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.033)</td>
<td style="text-align: center;">(0.036)</td>
<td style="text-align: center;">(0.055)</td>
</tr>
<tr class="odd">
<td>Divorced</td>
<td style="text-align: center;">0.087</td>
<td style="text-align: center;">-0.012</td>
<td style="text-align: center;">0.107</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.046)</td>
<td style="text-align: center;">(0.057)</td>
<td style="text-align: center;">(0.064)</td>
</tr>
<tr class="odd">
<td>Constant</td>
<td style="text-align: center;">1.668<sup>***</sup></td>
<td style="text-align: center;">1.648<sup>***</sup></td>
<td style="text-align: center;">1.506<sup>***</sup></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;">(0.102)</td>
<td style="text-align: center;">(0.126)</td>
<td style="text-align: center;">(0.170)</td>
</tr>
<tr class="odd">
<td>Observations</td>
<td style="text-align: center;">1434</td>
<td style="text-align: center;">751</td>
<td style="text-align: center;">683</td>
</tr>
<tr class="even">
<td><em>R</em><sup>2</sup></td>
<td style="text-align: center;">0.373</td>
<td style="text-align: center;">0.524</td>
<td style="text-align: center;">0.278</td>
</tr>
</tbody>
</table>
<p>Note: <sup>*</sup> <em>p</em> &lt; 0.05, <sup>**</sup> <em>p</em> &lt; 0.01, <sup>***</sup> <em>p</em> &lt; 0.001</p>
</div>
</figure>
</div>
<p>Conversely, the returns to experience are higher for women (6.2%) compared to men (3.0%). This result is somewhat surprising given the traditional narrative of women’s career interruptions leading to lower returns to experience. It may reflect changing patterns in women’s labor force attachment or selection effects in our sample.</p>
<p>The effect of marriage on wages differs starkly between men and women. For men, being married is associated with a 13.2% wage premium, while for women, it is associated with a 15.5% wage penalty. This finding echoes the “marriage premium” for men and “motherhood penalty” for women documented in previous literature <span class="citation" data-cites="killewald2013new">(<a href="#ref-killewald2013new" role="doc-biblioref">Killewald 2013</a>)</span>.</p>
<p>In conclusion, our analysis confirms the significant positive impacts of education and experience on wages, while also revealing important heterogeneities across the wage distribution and between genders. These findings have important implications for understanding wage determination and persistent wage gaps in the labor market.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study has examined the returns to education and experience in the contemporary labor market, providing new insights into the complex relationship between human capital investments and wage outcomes. Our findings both confirm established patterns and reveal new nuances in how education and experience shape earnings across different segments of the workforce.</p>
<p>Consistent with previous literature, we find substantial returns to both education and experience. An additional year of education is associated with an 8.1% increase in hourly wages, while an additional year of experience yields a 3.8% increase, with diminishing returns over time. These results underscore the continued importance of human capital investments in determining labor market outcomes.</p>
<p>Our quantile regression analyses reveal important heterogeneities in these returns across the wage distribution. The impact of education on wages is slightly stronger at the lower end of the distribution, suggesting that education may play a particularly crucial role in improving outcomes for lower-earning individuals. Conversely, the returns to experience are highest at the 25th percentile, indicating that additional experience is especially valuable for workers in the lower part of the wage distribution.</p>
<p>Gender differences in returns to education and experience persist, but in ways that challenge some traditional narratives. Women in our sample show higher returns to both education and experience compared to men. However, the substantial gender wage gap and the divergent effects of marriage on wages for men and women highlight the ongoing challenges in achieving gender equality in the labor market.</p>
<p>These findings have several important implications. First, they reinforce the value of education as a means of improving economic outcomes, particularly for those at the lower end of the wage distribution. Second, they highlight the need for policies that support continuous skill development and work experience accumulation throughout one’s career. Third, they underscore the complexity of gender disparities in the labor market, suggesting that addressing the gender wage gap requires nuanced approaches that go beyond equalizing educational attainment.</p>
<p>Our study also points to several avenues for future research. Further investigation into the mechanisms driving the higher returns to education and experience for women in our sample could yield valuable insights. Additionally, exploring how these returns vary across different occupations, industries, and over time could provide a more comprehensive understanding of labor market dynamics.</p>
<p>In conclusion, while education and experience remain crucial determinants of wages, their impacts are neither uniform nor straightforward. As the labor market continues to evolve, ongoing research will be essential to inform policies that promote equitable economic opportunities and outcomes for all workers.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-altonji1993effects" class="csl-entry" role="listitem">
Altonji, Joseph G. 1993. <span>“The Effects of High School Curriculum on Education and Labor Market Outcomes.”</span> <em>Journal of Human Resources</em>, 409–38.
</div>
<div id="ref-altonji2013heterogeneity" class="csl-entry" role="listitem">
Altonji, Joseph G, Erica Blom, and Costas Meghir. 2013. <span>“Heterogeneity in Human Capital Investments: High School Curriculum, College Major, and Careers.”</span> <em>Annual Review of Economics</em> 5 (1): 185–223.
</div>
<div id="ref-becker1964human" class="csl-entry" role="listitem">
Becker, Gary S. 1964. <em>Human Capital: A Theoretical and Empirical Analysis, with Special Reference to Education</em>. University of Chicago press.
</div>
<div id="ref-blau2017gender" class="csl-entry" role="listitem">
Blau, Francine D, and Lawrence M Kahn. 2017. <span>“The Gender Wage Gap: Extent, Trends, and Explanations.”</span> <em>Journal of Economic Literature</em> 55 (3): 789–865.
</div>
<div id="ref-card1999causal" class="csl-entry" role="listitem">
Card, David. 1999. <span>“The Causal Effect of Education on Earnings.”</span> <em>Handbook of Labor Economics</em> 3: 1801–63.
</div>
<div id="ref-diprete2006cumulative" class="csl-entry" role="listitem">
DiPrete, Thomas A, and Claudia Buchmann. 2006. <span>“The Growing Female Advantage in College Completion: The Role of Family Background and Academic Achievement.”</span> <em>American Sociological Review</em> 71 (4): 515–41.
</div>
<div id="ref-dustmann2004returns" class="csl-entry" role="listitem">
Dustmann, Christian, and Arthur Van Soest. 2004. <span>“Returns to Foreign Language Use Among Immigrants in Germany.”</span> <em>Labour Economics</em> 11 (3): 265–90.
</div>
<div id="ref-killewald2013new" class="csl-entry" role="listitem">
Killewald, Alexandra. 2013. <span>“A New Father’s Wage Premium: New Insights into the Role of Marriage, Human Capital, and Selection.”</span> <em>Demography</em> 50 (2): 421–48.
</div>
<div id="ref-koenker1978" class="csl-entry" role="listitem">
Koenker, Roger, and Gilbert Bassett. 1978. <span>“Regression Quantiles.”</span> <em>Econometrica</em> 46 (1): 33. <a href="https://doi.org/10.2307/1913643">https://doi.org/10.2307/1913643</a>.
</div>
<div id="ref-mincer1974schooling" class="csl-entry" role="listitem">
Mincer, Jacob. 1974. <span>“Schooling, Experience, and Earnings.”</span> <em>NBER Books</em>.
</div>
<div id="ref-murphy1992structure" class="csl-entry" role="listitem">
Murphy, Kevin M, and Finis Welch. 1992. <span>“The Structure of Wages.”</span> <em>The Quarterly Journal of Economics</em> 107 (1): 285–326.
</div>
<div id="ref-psacharopoulos2018returns" class="csl-entry" role="listitem">
Psacharopoulos, George, and Harry Anthony Patrinos. 2018. <span>“Returns to Investment in Education: A Decennial Review of the Global Literature.”</span> <em>Education Economics</em> 26 (5): 445–58.
</div>
<div id="ref-topel1991specific" class="csl-entry" role="listitem">
Topel, Robert. 1991. <span>“Specific Capital, Mobility, and Wages: Wages Rise with Job Seniority.”</span> <em>Journal of Political Economy</em> 99 (1): 145–76.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>